name: dt_medrhythm
description: A new Flutter project.

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.3
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.0
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3

flutter:
  uses-material-design: true

